#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
wmname LG3D &
feh --bg-fill /home/username/Fondos/Wallpaper.png &
~/.config/polybar/launch.sh &
killall mate-notification-daemon; dunst &

bspc config pointer_modifier mod1

bspc monitor -d I II III IV V VI VII VIII IX X

picom --experimental-backends &
bspc config border_width         1
bspc config window_gap           4 
bspc config normal_border_color  "#3EFE18"
bspc config focused_border_color  "#FEF418"
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Caja state=floating follow=on
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a burp-StartBurp: state=floating

bspc config focus_follows_pointer true
xsetroot -cursor_name left_ptr &
